# Site settings
title: Mensaplan der Uni Kassel
description: >
  Inoffizieller Mensaplan für die Mensen der Universität Kassel.
baseurl: "/canteen-ng"
url: "//nikeee.github.io"
github_username: nikeee
source_code_url: "//github.com/nikeee/canteen"
# Build settings
markdown: kramdown